# This zone allows delegation fo all `*.dev.example.org` records
# to the `development` namespace # and similarly allows adoption
# of DNS records matching `*.prod.example.org` from the `production`
# namespace.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
  delegations:
    - namespaces: ["development"]
      records:
        - pattern: "*.dev"
    - namespaces: ["production"]
      records:
        - pattern: "*.prod"

# This record will be adopted by the zone
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-dev-example-org
  namespace: development
spec:
  domainName: www.dev.example.org.
  type: A
  rdata: "192.168.0.2"

# This record won't be adopted by the zone, because it's a .prod record
# in the development namespace, which violates the delegation rules
# configured for the www-example zone.
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-prod-example-org
  namespace: development
spec:
  domainName: www.prod.example.org.
  type: A
  rdata: "192.168.0.2"
