# This example shows that if a zone has delegated away responsibility for a
# subzone, it cannot adopt records that rightfully belong in the subzone, even
# if the subzone's own delegation rules don't allow itself to adopt it.
#
# In cases like this where the subzone delegation is specified but not met,
# that is no Zone resources exist that assume responsibility for the subzone,
# the parent zone *will* adopt the records. WARNING: This could be considered
# a bug and might be changed in the future, such that any specified zone delegations
# prevent adoption of records, regardless of whether the delegation is met.

# This zone delegates way responsibility for the subzone "sub", but otherwise
# allows adoption of all child records.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
  delegations:
    - records:
        - pattern: "*"
    - zones: ["sub"]

# The sub-zone on the other hand only allows MX records.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: sub-example-org
spec:
  domainName: sub.example.org.
  delegations:
    - records:
        - pattern: "*"
          types: ["MX"]

# Even though the following record is allowed by `example-org`s delegation rules,
# because the "sub" subzone has been delegated, the zone won't adopt it, and it will
# remain orphaned.
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-sub-example-org
spec:
  domainName: www.sub.example.org.
  type: A
  rdata: "192.168.0.2"
