# Given two zones which allow delegation of a single record, the record will always be
# adopted by the zone with the longest name.

# This zone allows adoption of all records into itself, as well as the singular "sub" zone.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
  delegations:
    - records:
        - pattern: "*"
    - zones: ["sub"]

# example-org has delegated responsibility of the sub.example.org. domain to
# the following zone implicitly:
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: sub-example-org
spec:
  domainName: sub.example.org.
  delegations:
    - records:
        - pattern: "*"

# Even though this record is technically allowed to be adopted by both of the above zones
# the fact that sub.example.org is delegated *and* there's a Zone which fits that pattern,
# means that it is the only valid parent.
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-sub-example-org
spec:
  domainName: www.sub.example.org.
  type: A
  rdata: "192.168.0.2"
# NOTE! Deleting the sub-example-org zone at this point, would orphan the record, and since
# example-org is the only remaining valid parent, it would adopt the record.
#
# Should the sub-example-org Zone then get recreated, it would of course again become the longest
# matching zone, and therefore adopt the record again from its parent.
