# This zone does not allow any kind of delegation, which makes it pretty useless.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
  delegations: []

# This record won't be adopted, since the zone does not allow any delegation.
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-example-org
spec:
  domainName: www.example.org.
  type: A
  rdata: "192.168.0.2"
