# This zone allows delegation of all record types records to all namespaces.
---
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
  delegations:
    - records:
        - pattern: "*"

# This record will be adopted by the example-org zone and included in its list of zone entries.
---
apiVersion: kubi.zone/v1alpha1
kind: Record
metadata:
  name: www-example-org
spec:
  domainName: www.example.org.
  type: A
  rdata: "192.168.0.2"
