on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test, build, publish

jobs:
  lint:
    name: linting (rustfmt + clippy)
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt,clippy

      - name: run rustfmt
        run: cargo fmt --all -- --check
      
      - name: run clippy
        run: cargo clippy --all-features

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      
      - name: run cargo test
        run: cargo test --all-features

  build-operators:
    needs: [lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: build operators
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up qemu
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to github packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/kubi-zone/kubizone
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/kubi-zone/kubizone:buildcache
          cache-to: type=registry,ref=ghcr.io/kubi-zone/kubizone:buildcache,mode=max

      - name: fetch crate version
        id: crate-version
        uses: colathro/crate-version@1.0.0
        with:
          file: "./Cargo.toml"

      - name: tag with crate version
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          custom_tag: ${{ steps.crate-version.outputs.version }}

      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: "refs/tags/v${{ steps.crate-version.outputs.version }}"
